/**
 * 历史回放的 source 改写(`restoreReplaySources`)、跨路由思考摘除,与路由切换通知
 * (`appendRouteSwitchNotice`)。
 *
 * 第一批(旧行为,不传 route):路由不同 ⇒ 改写、相同 ⇒ 原样、无 replayState ⇒ 原样、
 * 形状不对 ⇒ 原样不抛、`content` 与其它字段逐字未变;外加逐条独立取值、非助手消息不动、
 * 冻结输入不被破坏。
 *
 * 第二批(2026-09-28 修法 A,清单见 `auto-route-capture/FIX-A-DESIGN.md` §4.2 的 16 条):
 * 跨路由 ⇒ `content` 与 `replayState.blocks` **同步**摘 reasoning、摘后 `replayedAssistant`
 * 的四条校验仍过(含"只摘一侧 ⇒ 等长校验失败"的反例)、正文与工具调用块一个不动、redacted
 * 思考同样摘、信封对不齐 ⇒ 摘 content 并丢整个 replayState、摘空 ⇒ 整条消息去掉、同路由零改动、
 * 不传 route ⇒ 退化为旧行为、anthropic 的 `responseModel` 重建规则、非 pi-ai 信封、
 * 会话中途切过多次、浅冻结与引用、坏形状不抛。
 *
 * 第三批(修法 B):发生切换 ⇒ 追加同款通知、未切换 ⇒ 不追加、历史已有覆盖本次切换的通知 ⇒
 * 不重复追加、路由标签规则(同 provider 只写 model / 不同 provider 写 provider/model)、
 * 通知只进嵌套请求而不动外层请求。
 */
import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { appendRouteSwitchNotice, appendToolLoopBreak, AutoAdapter, createRing, restoreReplaySources } from '../lib/index.js'

/** 一条"经 auto 产出"的历史助手消息:source 记 auto,replay 状态记真实路由。 */
function autoAssistant(overrides = {}) {
  const { source: sourceOverride, ...rest } = overrides
  return Object.freeze({
    role: 'assistant',
    content: Object.freeze([
      Object.freeze({ type: 'reasoning', text: '先算 17*23 = 391' }),
      Object.freeze({ type: 'text', text: '12121' }),
    ]),
    source: Object.freeze({
      kind: 'model',
      provider: 'auto',
      model: 'auto',
      replayState: Object.freeze({
        response: Object.freeze({
          kind: 'pi-ai',
          version: 2,
          api: 'openai-completions',
          provider: 'opencode-go',
          model: 'deepseek-v4.1-flash',
          stopReason: 'stop',
        }),
        blocks: Object.freeze([Object.freeze({ type: 'reasoning' }), Object.freeze({ type: 'text' })]),
      }),
      ...sourceOverride,
    }),
    ...rest,
  })
}

/** 造一个请求(默认:system + 一条待改写的历史助手消息 + user)。 */
function request(messages) {
  return Object.freeze({
    provider: 'auto',
    model: 'auto',
    messages: Object.freeze(messages ?? [
      Object.freeze({ role: 'system', content: 'sys' }),
      autoAssistant(),
      Object.freeze({ role: 'user', content: '追问' }),
    ]),
  })
}

/** 夹具默认那条历史消息的回放路由(与 `autoAssistant()` 的 replay 响应一致)。 */
const ROUTE = Object.freeze({ provider: 'opencode-go', model: 'deepseek-v4.1-flash' })
/** 链上第二条路由:拿它当"本次候选路由"就是跨路由。 */
const STEPFUN = Object.freeze({ provider: 'stepfun', model: 'step-5-preview' })
/** 与 {@link STEPFUN} 对应的 replay 响应头。 */
const STEPFUN_RESPONSE = Object.freeze({
  kind: 'pi-ai', version: 2, api: 'openai-completions', provider: 'stepfun', model: 'step-5-preview', stopReason: 'stop',
})
/** 与 {@link ROUTE} 对应的 replay 响应头。 */
const REPLAY_RESPONSE = Object.freeze({
  kind: 'pi-ai', version: 2, api: 'openai-completions', provider: 'opencode-go', model: 'deepseek-v4.1-flash', stopReason: 'stop',
})
/** `[reasoning, text]` 的 replay 块序列(与夹具默认 content 同位同型)。 */
const REASONING_THEN_TEXT = Object.freeze([Object.freeze({ type: 'reasoning' }), Object.freeze({ type: 'text' })])

/**
 * `dsh-llm-pi-ai` 的 `replayedAssistant` 校验复刻(`lib/index.js:185`/`:186`/`:187`/`:192`)。
 *
 * 为什么要复刻:真函数没有导出,而这四条校验正是"必须两侧同步摘"的**全部**理由 ——
 * 把 FIX-A-DESIGN.md §2.5 的推导钉成回归,比只断言"块数变少了"结实得多。
 * 错误描述与上游逐字同款,便于对照宿主日志里的 `llm-pi-ai: unusable replay state`。
 *
 * @param message - 待校验的历史助手消息。
 * @returns 全部通过时 null;否则返回命中的那条校验的错误描述。
 */
function replayedAssistantCheck(message) {
  const source = message.source
  const state = source?.replayState
  if (state === undefined) return 'no replay state'
  if (state.response.provider !== source.provider) return 'provider does not match assistant source'
  if (state.response.model !== source.model) return 'model does not match assistant source'
  if (state.blocks.length !== message.content.length) return 'block count does not match assistant content'
  for (let index = 0; index < state.blocks.length; index += 1) {
    if (state.blocks[index].type !== message.content[index].type) return `block ${index} does not match assistant content`
  }
  return null
}

/**
 * 造一条带指定 replay 信封的历史助手消息。
 * @param response - `replayState.response`。
 * @param blocks - `replayState.blocks`;不传 = **缺 blocks**(用来测"信封对不齐")。
 * @param content - 覆盖默认 content;不传 = 夹具默认的 `[reasoning, text]`。
 * @returns 深冻结的助手消息。
 */
function assistantWithEnvelope(response, blocks, content) {
  return autoAssistant({
    ...(content === undefined ? {} : { content }),
    source: {
      provider: 'auto',
      model: 'auto',
      replayState: { response, ...(blocks === undefined ? {} : { blocks }) },
    },
  })
}

/** 造一条 DSH 自带的路由切换通知(措辞与 source 标记都与 `modelSwitchNotice` 逐字同款)。 */
function builtinNotice(from, to) {
  return Object.freeze({
    role: 'user',
    content: Object.freeze([Object.freeze({
      type: 'text',
      text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`,
    })]),
    source: Object.freeze({ kind: 'model-selection', form: 'notice', summary: `${from} → ${to}` }),
  })
}

describe('restoreReplaySources:改写', () => {
  it('replay 路由与 source 不同 ⇒ provider/model 改成 replay 记录的真实路由', () => {
    const options = request()
    const fixed = restoreReplaySources(options)
    assert.notEqual(fixed, options)
    assert.equal(fixed.messages[1].source.provider, 'opencode-go')
    assert.equal(fixed.messages[1].source.model, 'deepseek-v4.1-flash')
    // replayState 原样带着走(下游 forAdapter 要靠它保留)
    assert.equal(fixed.messages[1].source.replayState, options.messages[1].source.replayState)
  })

  it('只改 provider/model,content 与其它字段逐字未变(原消息不被破坏)', () => {
    const options = request()
    const before = options.messages[1]
    const after = restoreReplaySources(options).messages[1]
    assert.equal(after.content, before.content) // content 同一引用 ⇒ 逐字未变
    const strip = (message) => JSON.stringify({ ...message, source: undefined })
    assert.equal(strip(after), strip(before))
    assert.deepEqual(Object.keys(after).sort(), Object.keys(before).sort())
    assert.deepEqual(Object.keys(after.source).sort(), Object.keys(before.source).sort())
    // 入参(深冻结)保持原值
    assert.equal(before.source.provider, 'auto')
    assert.equal(before.source.model, 'auto')
  })

  it('改出来的消息与 source 都是浅冻结的(与宿主"消息不可变"的约定一致)', () => {
    const after = restoreReplaySources(request()).messages[1]
    assert.equal(Object.isFrozen(after), true)
    assert.equal(Object.isFrozen(after.source), true)
  })

  it('多条历史消息各自按自己的 replay 路由改写(会话中途切过路由)', () => {
    const first = autoAssistant()
    const second = autoAssistant({
      source: {
        provider: 'auto',
        model: 'auto',
        replayState: {
          response: { kind: 'pi-ai', version: 2, api: 'openai-completions', provider: 'commandcode', model: 'deepseek/deepseek-v4.1-flash', stopReason: 'stop' },
          blocks: [{ type: 'reasoning' }, { type: 'text' }],
        },
      },
    })
    const fixed = restoreReplaySources(request([first, second]))
    assert.deepEqual(
      fixed.messages.map((m) => `${m.source.provider}/${m.source.model}`),
      ['opencode-go/deepseek-v4.1-flash', 'commandcode/deepseek/deepseek-v4.1-flash'],
    )
  })

  it('数组只在真的需要改时才复制:未改写的消息保持同一引用', () => {
    const untouched = Object.freeze({ role: 'user', content: 'hi' })
    const options = request([untouched, autoAssistant()])
    const fixed = restoreReplaySources(options)
    assert.notEqual(fixed.messages, options.messages)
    assert.equal(fixed.messages[0], untouched) // 不需要改的那条原样进新数组
    assert.notEqual(fixed.messages[1], options.messages[1]) // 需要改的那条是新对象
    assert.equal(fixed.messages[1].content, options.messages[1].content) // 但 content 是同一份
    assert.equal(options.messages[1].source.provider, 'auto') // 入参那条仍是旧 source
  })
})

describe('restoreReplaySources:原样放行', () => {
  it('replay 路由与 source 相同 ⇒ 返回同一个 options 对象(零改动)', () => {
    const message = autoAssistant({
      source: {
        provider: 'opencode-go',
        model: 'deepseek-v4.1-flash',
        replayState: {
          response: { kind: 'pi-ai', version: 2, api: 'openai-completions', provider: 'opencode-go', model: 'deepseek-v4.1-flash', stopReason: 'stop' },
          blocks: [{ type: 'reasoning' }, { type: 'text' }],
        },
      },
    })
    const options = request([message])
    const fixed = restoreReplaySources(options)
    assert.equal(fixed, options)
    assert.equal(fixed.messages[0], message)
  })

  it('没有 replayState ⇒ 原样', () => {
    const options = request([Object.freeze({ role: 'assistant', content: [], source: Object.freeze({ kind: 'model', provider: 'auto', model: 'auto' }) })])
    assert.equal(restoreReplaySources(options), options)
  })

  it('非助手消息即使带 replayState 也不动', () => {
    const user = Object.freeze({
      role: 'user',
      content: 'hi',
      source: Object.freeze({ kind: 'model', provider: 'auto', model: 'auto', replayState: Object.freeze({ response: Object.freeze({ provider: 'opencode-go', model: 'deepseek-v4.1-flash' }) }) }),
    })
    const options = request([user])
    assert.equal(restoreReplaySources(options), options)
  })

  it('replayState 形状不对 ⇒ 原样返回且不抛', () => {
    const cases = [
      undefined,
      null,
      'not-an-object',
      42,
      {},
      { response: null },
      { response: 'nope' },
      { response: [] },
      { response: {} }, // 缺 provider/model
      { response: { provider: 'opencode-go' } }, // 缺 model
      { response: { provider: '', model: 'deepseek-v4.1-flash' } }, // 空串
      { response: { provider: 'opencode-go', model: '' } },
      { response: { provider: 7, model: 'deepseek-v4.1-flash' } },
      { response: { provider: 'opencode-go', model: { id: 'x' } } },
    ]
    for (const replayState of cases) {
      const message = Object.freeze({ role: 'assistant', content: [], source: Object.freeze({ kind: 'model', provider: 'auto', model: 'auto', ...(replayState === undefined ? {} : { replayState }) }) })
      const options = request([message])
      assert.equal(restoreReplaySources(options), options, `replayState=${JSON.stringify(replayState)} 应原样放行`)
    }
  })

  it('messages 不是数组 / options 不是对象 ⇒ 原样返回不抛', () => {
    for (const bad of [undefined, null, 'x', 7, {}, { messages: null }, { messages: 'nope' }, { messages: {} }]) {
      assert.equal(restoreReplaySources(bad), bad)
    }
  })

  it('source 缺失或不是对象 ⇒ 原样', () => {
    for (const source of [undefined, null, 'x', 7]) {
      const options = request([Object.freeze({ role: 'assistant', content: [], ...(source === undefined ? {} : { source }) })])
      assert.equal(restoreReplaySources(options), options)
    }
  })
})


describe('restoreReplaySources:跨路由摘思考(2026-09-28 修法 A)', () => {
  it('跨路由 ⇒ reasoning 块从 content 与 replayState.blocks 同位摘掉', () => {
    const options = request()
    const before = options.messages[1]
    const after = restoreReplaySources(options, STEPFUN).messages[1]
    assert.notEqual(after, before)
    assert.deepEqual(after.content.map((block) => block.type), ['text'])
    assert.deepEqual(after.source.replayState.blocks.map((block) => block.type), ['text'])
    assert.equal(after.content[0].text, '12121') // 正文逐字保留
    assert.equal(after.source.provider, 'opencode-go') // source 仍按修法① 对齐到 replay 路由
    assert.equal(after.source.model, 'deepseek-v4.1-flash')
    // 入参(深冻结)未被破坏
    assert.deepEqual(before.content.map((block) => block.type), ['reasoning', 'text'])
    assert.deepEqual(before.source.replayState.blocks.map((block) => block.type), ['reasoning', 'text'])
  })

  it('同步摘之后 replayedAssistant 的校验仍全部通过(等长 + 逐条同型)', () => {
    const crossed = restoreReplaySources(request(), STEPFUN).messages[1]
    assert.equal(replayedAssistantCheck(crossed), null)
    // 同路由(不摘)那条也通过 ⇒ 摘除没有破坏信封本身
    const kept = restoreReplaySources(request(), ROUTE).messages[1]
    assert.equal(replayedAssistantCheck(kept), null)
  })

  it('只摘 content 一侧(反例)⇒ 等长校验失败 ⇒ 整条降级', () => {
    const aligned = restoreReplaySources(request(), ROUTE).messages[1]
    assert.equal(replayedAssistantCheck(aligned), null) // 先证:信封本身是合法的
    const halfStripped = Object.freeze({
      ...aligned,
      content: Object.freeze(aligned.content.filter((block) => block.type !== 'reasoning')),
    })
    assert.equal(replayedAssistantCheck(halfStripped), 'block count does not match assistant content')
  })

  it('正文与工具调用块一个不动(只摘 reasoning)', () => {
    const message = autoAssistant({
      content: Object.freeze([
        Object.freeze({ type: 'reasoning', text: '想想', thinkingSignature: 'sig-think' }),
        Object.freeze({ type: 'text', text: '算好了', textSignature: 'sig-text' }),
        Object.freeze({ type: 'tool-call', id: 'call-1', name: 'read_image', arguments: '{"path":"a.png"}' }),
      ]),
      source: {
        provider: 'auto',
        model: 'auto',
        replayState: {
          response: { kind: 'pi-ai', version: 2, api: 'openai-completions', provider: 'opencode-go', model: 'deepseek-v4.1-flash', stopReason: 'toolUse' },
          blocks: [
            { type: 'reasoning', thinkingSignature: 'sig-think' },
            { type: 'text', textSignature: 'sig-text' },
            { type: 'tool-call', thoughtSignature: 'sig-thought' },
          ],
        },
      },
    })
    const after = restoreReplaySources(request([message]), STEPFUN).messages[0]
    assert.deepEqual(after.content.map((block) => block.type), ['text', 'tool-call'])
    assert.deepEqual(after.source.replayState.blocks.map((block) => block.type), ['text', 'tool-call'])
    assert.equal(after.content[1].id, 'call-1')
    assert.equal(after.content[1].name, 'read_image')
    assert.equal(after.content[1].arguments, '{"path":"a.png"}')
    assert.equal(after.source.replayState.blocks[0].textSignature, 'sig-text') // 信封里的正文签名还在
    assert.equal(replayedAssistantCheck(after), null)
  })

  it('redacted 思考同样摘掉', () => {
    const message = autoAssistant({
      content: Object.freeze([
        Object.freeze({ type: 'reasoning', text: '', redacted: true }),
        Object.freeze({ type: 'text', text: '结论' }),
      ]),
      source: {
        provider: 'auto',
        model: 'auto',
        replayState: {
          response: { kind: 'pi-ai', version: 2, api: 'openai-completions', provider: 'opencode-go', model: 'deepseek-v4.1-flash', stopReason: 'stop' },
          blocks: [{ type: 'reasoning', redacted: true }, { type: 'text' }],
        },
      },
    })
    const after = restoreReplaySources(request([message]), STEPFUN).messages[0]
    assert.deepEqual(after.content.map((block) => block.type), ['text'])
    assert.deepEqual(after.source.replayState.blocks.map((block) => block.type), ['text'])
    assert.equal(replayedAssistantCheck(after), null)
  })

  it('信封与 content 对不齐(缺 blocks / 长度错位 / 类型错位)⇒ 摘 content 并丢整个 replayState', () => {
    const envelopes = [
      { response: REPLAY_RESPONSE }, // 缺 blocks
      { response: REPLAY_RESPONSE, blocks: [{ type: 'reasoning' }] }, // 长度错位(少)
      { response: REPLAY_RESPONSE, blocks: [{ type: 'reasoning' }, { type: 'text' }, { type: 'text' }] }, // 长度错位(多)
      { response: REPLAY_RESPONSE, blocks: [{ type: 'text' }, { type: 'text' }] }, // 类型错位
      { response: REPLAY_RESPONSE, blocks: 'nope' }, // 形状不对
    ]
    for (const replayState of envelopes) {
      const label = JSON.stringify(replayState)
      const message = autoAssistant({ source: { provider: 'auto', model: 'auto', replayState } })
      const after = restoreReplaySources(request([message]), STEPFUN).messages[0]
      assert.deepEqual(after.content.map((block) => block.type), ['text'], label) // 思考摘掉
      assert.equal(after.source.replayState, undefined, label) // 不留半截信封
      assert.equal(after.source.provider, 'opencode-go', label)
      assert.equal(after.source.model, 'deepseek-v4.1-flash', label)
    }
  })

  it('摘完一个块都不剩 ⇒ 整条消息从请求里去掉', () => {
    const onlyThinking = assistantWithEnvelope(
      REPLAY_RESPONSE,
      [{ type: 'reasoning' }],
      Object.freeze([Object.freeze({ type: 'reasoning', text: '只有内心独白' })]),
    )
    const untouched = Object.freeze({ role: 'user', content: 'hi' })
    const options = request([untouched, onlyThinking, Object.freeze({ role: 'user', content: '追问' })])
    const fixed = restoreReplaySources(options, STEPFUN)
    assert.equal(fixed.messages.length, 2)
    assert.equal(fixed.messages[0], untouched) // 未改动的消息保持同一引用
    assert.equal(fixed.messages[1].content, '追问')
    assert.equal(options.messages.length, 3) // 入参未被破坏
  })

  it('anthropic 路由:responseModel ≠ 请求 model ⇒ 也算跨模型,照摘', () => {
    const message = assistantWithEnvelope(
      { kind: 'pi-ai', version: 2, api: 'anthropic-messages', provider: 'opencode-go', model: 'deepseek-v4.1-flash', responseModel: 'claude-sonnet-4-5', stopReason: 'stop' },
      REASONING_THEN_TEXT,
    )
    // provider/model 与候选一致,但 pi-ai 重建后的 model 是 responseModel(`PI:218`)⇒ 不同 ⇒ 摘
    const crossed = restoreReplaySources(request([message]), ROUTE).messages[0]
    assert.deepEqual(crossed.content.map((block) => block.type), ['text'])
    assert.equal(crossed.source.model, 'deepseek-v4.1-flash') // source 仍写 response.model(`PI:186` 校验它)
    // 反过来:候选 model 就是重建出来的那个 ⇒ 同模型 ⇒ 连引用都不换
    const kept = restoreReplaySources(request([message]), { provider: 'opencode-go', model: 'claude-sonnet-4-5' }).messages[0]
    assert.equal(kept.content, message.content)
    assert.deepEqual(kept.content.map((block) => block.type), ['reasoning', 'text'])
  })

  it('非 pi-ai 信封(kind: deepseek-messages)跨路由也摘;同路由不动', () => {
    const message = assistantWithEnvelope(
      { kind: 'deepseek-messages', version: 1, provider: 'deepseek-official', model: 'deepseek-flash', stopReason: 'stop' },
      REASONING_THEN_TEXT,
    )
    const crossed = restoreReplaySources(request([message]), STEPFUN).messages[0]
    assert.deepEqual(crossed.content.map((block) => block.type), ['text'])
    const same = restoreReplaySources(request([message]), { provider: 'deepseek-official', model: 'deepseek-flash' }).messages[0]
    assert.equal(same.content, message.content) // 同路由 ⇒ 连引用都不换
  })

  it('会话中途切过多次 ⇒ 每条按自己的回放路由决定摘不摘', () => {
    const crossed = autoAssistant() // replay 路由 = opencode-go
    const same = assistantWithEnvelope(STEPFUN_RESPONSE, REASONING_THEN_TEXT)
    const fixed = restoreReplaySources(request([crossed, same]), STEPFUN)
    assert.deepEqual(fixed.messages[0].content.map((block) => block.type), ['text']) // 跨路由 ⇒ 摘
    assert.equal(fixed.messages[1].content, same.content) // 同路由 ⇒ 引用未换
    assert.deepEqual(fixed.messages[1].content.map((block) => block.type), ['reasoning', 'text'])
  })

  it('改出来的消息与 source 都是浅冻结的;content 只在真摘过时才是新数组', () => {
    const options = request()
    const before = options.messages[1]
    const crossed = restoreReplaySources(options, STEPFUN).messages[1]
    assert.notEqual(crossed.content, before.content)
    for (const value of [crossed, crossed.source, crossed.content, crossed.source.replayState, crossed.source.replayState.blocks]) {
      assert.equal(Object.isFrozen(value), true)
    }
    const kept = restoreReplaySources(options, ROUTE).messages[1]
    assert.equal(kept.content, before.content) // 没摘 ⇒ content 是原引用
    assert.equal(kept.source.replayState, before.source.replayState)
  })

  it('同路由 + source 已一致 ⇒ 返回同一个 options(零改动)', () => {
    const message = autoAssistant({
      source: { provider: 'opencode-go', model: 'deepseek-v4.1-flash', replayState: { response: REPLAY_RESPONSE, blocks: REASONING_THEN_TEXT } },
    })
    const options = request([message])
    const fixed = restoreReplaySources(options, ROUTE)
    assert.equal(fixed, options)
    assert.equal(fixed.messages[0], message)
    assert.equal(fixed.messages[0].content, message.content)
  })

  it('同路由但 source 还是 auto ⇒ 只改 source,content 与 replayState 引用都不换', () => {
    const options = request()
    const before = options.messages[1]
    const after = restoreReplaySources(options, ROUTE).messages[1]
    assert.notEqual(after, before)
    assert.equal(after.source.provider, 'opencode-go')
    assert.equal(after.source.model, 'deepseek-v4.1-flash')
    assert.equal(after.content, before.content) // content 引用未换
    assert.equal(after.source.replayState, before.source.replayState) // replayState 引用未换
    assert.deepEqual(after.content.map((block) => block.type), ['reasoning', 'text']) // 思考原样保留
  })

  it('不传 route ⇒ 退化为旧行为(只改 source,不摘思考)', () => {
    const options = request()
    const before = options.messages[1]
    const after = restoreReplaySources(options).messages[1]
    assert.equal(after.content, before.content)
    assert.equal(after.source.replayState, before.source.replayState)
    assert.deepEqual(after.content.map((block) => block.type), ['reasoning', 'text'])
  })

  it('入参深冻结且形状不全时不抛(有路由值但信封缺 blocks / 空 blocks / 空 responseModel)', () => {
    // 这些形状**不是**"纯粹的坏形状"(provider/model 是合法非空字符串),所以不能并进上面那张
    // "形状不对 ⇒ 原样放行"的表 —— 传 route 时它们会被真的改写。这里钉三件事:
    // ① 不传 route 仍是旧行为(只改 source);② 传 route 绝不抛且信封不全就整个丢掉;
    // ③ 入参(深冻结)始终未被破坏。
    const shapes = [
      { response: { provider: 'opencode-go', model: 'deepseek-v4.1-flash' } }, // 有路由值,没 blocks
      { response: REPLAY_RESPONSE, blocks: [] }, // 空 blocks
      { response: { kind: 'pi-ai', version: 2, api: 'anthropic-messages', provider: 'opencode-go', model: 'deepseek-v4.1-flash' } }, // anthropic 没 responseModel
      { response: { kind: 'pi-ai', version: 2, api: 'anthropic-messages', provider: 'opencode-go', model: 'deepseek-v4.1-flash', responseModel: '' } }, // 空 responseModel
    ]
    for (const replayState of shapes) {
      const label = JSON.stringify(replayState)
      const message = autoAssistant({ source: { provider: 'auto', model: 'auto', replayState } })
      const options = request([message])
      const legacy = restoreReplaySources(options)
      assert.notEqual(legacy, options, label)
      assert.equal(legacy.messages[0].source.provider, 'opencode-go', label)
      assert.equal(legacy.messages[0].source.replayState, replayState, label) // 旧行为不碰信封
      const fixed = restoreReplaySources(options, STEPFUN)
      assert.equal(fixed.messages[0].source.replayState, undefined, label)
      assert.deepEqual(fixed.messages[0].content.map((block) => block.type), ['text'], label)
      // 入参(深冻结)始终未被破坏
      assert.equal(options.messages[0].content, message.content, label)
      assert.deepEqual(message.content.map((block) => block.type), ['reasoning', 'text'], label)
      assert.equal(message.source.replayState, replayState, label)
    }
  })
})

describe('接线:嵌套调用真的拿到了改写后的 source', () => {
  /** 只记录嵌套请求的假 llm(不用 helpers 的通用替身,这里要看 messages)。 */
  function capturingLlm(seen) {
    return {
      async *stream(options) {
        seen.push(options)
        yield { type: 'block-start', index: 0, blockType: 'text' }
        yield { type: 'text-delta', index: 0, text: 'ok' }
        yield { type: 'block-end', index: 0, block: { type: 'text', text: 'ok' } }
        yield { type: 'finish', reason: { kind: 'stop' } }
      },
      async resolveModelInfo(provider, model) {
        return { provider, id: model, name: model, context: { contextWindow: 1000 } }
      },
    }
  }

  it('AutoAdapter.stream() 交给 llm.stream 的历史助手消息已改回真实路由', async () => {
    const seen = []
    const adapter = new AutoAdapter({
      llm: capturingLlm(seen),
      routes: [{ provider: 'opencode-go', model: 'deepseek-v4.1-flash' }],
      modelName: 'Auto',
      ring: createRing(5),
      logger: { info: () => {}, warn: () => {}, error: () => {} },
      resolveContextWindow: async () => 1000,
    })
    const options = request()
    for await (const _chunk of adapter.stream(options)) { /* 只关心嵌套请求长什么样 */ }

    assert.equal(seen.length, 1)
    assert.equal(seen[0].provider, 'opencode-go')
    assert.equal(seen[0].messages[1].source.provider, 'opencode-go')
    assert.equal(seen[0].messages[1].source.model, 'deepseek-v4.1-flash')
    assert.equal(seen[0].messages[1].content, options.messages[1].content) // content 逐字未变
    assert.equal(options.messages[1].source.provider, 'auto') // 外层请求没被改
  })

  it('AutoAdapter 的嵌套请求里,跨路由历史的思考已被摘掉(钉住 adapter 的传参)', async () => {
    const seen = []
    const adapter = new AutoAdapter({
      llm: capturingLlm(seen),
      routes: [{ provider: 'stepfun', model: 'step-5-preview' }],
      modelName: 'Auto',
      ring: createRing(5),
      logger: { info: () => {}, warn: () => {}, error: () => {} },
      resolveContextWindow: async () => 1000,
    })
    const options = request()
    for await (const _chunk of adapter.stream(options)) { /* 只关心嵌套请求长什么样 */ }

    assert.equal(seen.length, 1)
    assert.equal(seen[0].provider, 'stepfun')
    assert.deepEqual(seen[0].messages[1].content.map((block) => block.type), ['text'])
    assert.deepEqual(seen[0].messages[1].source.replayState.blocks.map((block) => block.type), ['text'])
    assert.equal(replayedAssistantCheck(seen[0].messages[1]), null)
    // 外层请求一个字都没动
    assert.deepEqual(options.messages[1].content.map((block) => block.type), ['reasoning', 'text'])
  })

  it('AutoAdapter 的嵌套请求末尾带了切换通知,且外层请求没有被改', async () => {
    const seen = []
    const adapter = new AutoAdapter({
      llm: capturingLlm(seen),
      routes: [{ provider: 'stepfun', model: 'step-5-preview' }],
      modelName: 'Auto',
      ring: createRing(5),
      logger: { info: () => {}, warn: () => {}, error: () => {} },
      resolveContextWindow: async () => 1000,
    })
    const options = request()
    for await (const _chunk of adapter.stream(options)) { /* 只关心嵌套请求长什么样 */ }

    assert.equal(seen[0].messages.length, 4)
    assert.equal(
      seen[0].messages[3].content[0].text,
      '[model changed: assistant turns above this point were generated by opencode-go/deepseek-v4.1-flash; the session continues with stepfun/step-5-preview]',
    )
    assert.equal(seen[0].messages[3].source.kind, 'model-selection')
    assert.equal(options.messages.length, 3) // 通知只在出站副本里,不落进外层请求/会话记录
  })
})

describe('appendRouteSwitchNotice:路由切换通知(2026-09-28 修法 B)', () => {
  it('真的发生切换 ⇒ 在出站消息序列末尾追加一条同款通知', () => {
    const options = request()
    const fixed = appendRouteSwitchNotice(options, STEPFUN)
    assert.notEqual(fixed, options)
    assert.equal(fixed.messages.length, options.messages.length + 1)
    const notice = fixed.messages[fixed.messages.length - 1]
    assert.equal(notice.role, 'user')
    assert.equal(
      notice.content[0].text,
      '[model changed: assistant turns above this point were generated by opencode-go/deepseek-v4.1-flash; the session continues with stepfun/step-5-preview]',
    )
    assert.equal(notice.source.kind, 'model-selection')
    assert.equal(notice.source.form, 'notice')
    assert.equal(notice.source.summary, 'opencode-go/deepseek-v4.1-flash → stepfun/step-5-preview')
    assert.equal(Object.isFrozen(notice), true)
    assert.equal(Object.isFrozen(notice.content), true)
    assert.equal(Object.isFrozen(notice.content[0]), true)
    // 原有消息逐条保持同一引用;入参未被破坏(通知不落进会话记录)
    assert.equal(fixed.messages[0], options.messages[0])
    assert.equal(fixed.messages[1], options.messages[1])
    assert.equal(fixed.messages[2], options.messages[2])
    assert.equal(options.messages.length, 3)
  })

  it('路由没变 ⇒ 不追加(返回同一个 options)', () => {
    const options = request()
    assert.equal(appendRouteSwitchNotice(options, ROUTE), options)
  })

  it('路由标签规则:provider 相同就只写 model', () => {
    const fixed = appendRouteSwitchNotice(request(), { provider: 'opencode-go', model: 'gpt-6-astra' })
    const notice = fixed.messages[fixed.messages.length - 1]
    assert.equal(
      notice.content[0].text,
      '[model changed: assistant turns above this point were generated by deepseek-v4.1-flash; the session continues with gpt-6-astra]',
    )
    assert.equal(notice.source.summary, 'deepseek-v4.1-flash → gpt-6-astra')
  })

  it('路由标签规则:provider 不同就写 provider/model(两侧各按对方判)', () => {
    const message = assistantWithEnvelope(STEPFUN_RESPONSE, REASONING_THEN_TEXT)
    const fixed = appendRouteSwitchNotice(request([message]), ROUTE)
    const notice = fixed.messages[fixed.messages.length - 1]
    assert.equal(
      notice.content[0].text,
      '[model changed: assistant turns above this point were generated by stepfun/step-5-preview; the session continues with opencode-go/deepseek-v4.1-flash]',
    )
    assert.equal(notice.source.summary, 'stepfun/step-5-preview → opencode-go/deepseek-v4.1-flash')
  })

  it('历史里已有覆盖本次切换的自带通知 ⇒ 不重复追加', () => {
    const options = request([
      autoAssistant(),
      builtinNotice('opencode-go/deepseek-v4.1-flash', 'auto'),
      Object.freeze({ role: 'user', content: '追问' }),
    ])
    assert.equal(appendRouteSwitchNotice(options, STEPFUN), options)
  })

  it('自带通知描述的是另一个来源 ⇒ 仍然追加', () => {
    const options = request([
      autoAssistant(),
      builtinNotice('stepfun/step-5-preview', 'auto'),
      Object.freeze({ role: 'user', content: '追问' }),
    ])
    const fixed = appendRouteSwitchNotice(options, STEPFUN)
    assert.notEqual(fixed, options)
    assert.equal(fixed.messages.length, 4)
  })

  it('自带通知出现在最后一条助手消息之前 ⇒ 不算覆盖(它说的是更早那批回合)', () => {
    const options = request([
      autoAssistant(),
      builtinNotice('opencode-go/deepseek-v4.1-flash', 'auto'),
      autoAssistant(),
      Object.freeze({ role: 'user', content: '追问' }),
    ])
    const fixed = appendRouteSwitchNotice(options, STEPFUN)
    assert.notEqual(fixed, options)
    assert.equal(fixed.messages.length, 5)
  })

  it('没有助手消息 / 上一条助手消息没有可用回放路由 ⇒ 不追加(判不出切换就不声称切换)', () => {
    const noAssistant = request([Object.freeze({ role: 'user', content: 'hi' })])
    assert.equal(appendRouteSwitchNotice(noAssistant, STEPFUN), noAssistant)
    const noReplay = request([Object.freeze({
      role: 'assistant',
      content: Object.freeze([Object.freeze({ type: 'text', text: 'ok' })]),
      source: Object.freeze({ kind: 'model', provider: 'auto', model: 'auto' }),
    })])
    assert.equal(appendRouteSwitchNotice(noReplay, STEPFUN), noReplay)
  })

  it('坏入参不抛(route / options / messages 形状不对)', () => {
    const options = request()
    const badRoutes = [undefined, null, 'x', 7, {}, [], { provider: 'stepfun' }, { provider: '', model: 'x' }, { provider: 'stepfun', model: '' }, { provider: 'stepfun', model: 7 }]
    for (const bad of badRoutes) {
      assert.equal(appendRouteSwitchNotice(options, bad), options, `route=${JSON.stringify(bad)} 应原样返回`)
    }
    for (const bad of [undefined, null, 'x', 7, {}, { messages: null }, { messages: [] }, { messages: 'nope' }]) {
      assert.equal(appendRouteSwitchNotice(bad, STEPFUN), bad)
    }
  })

  it('追加的通知本身不会被同一次调用重复追加(逐次尝试都从原始 options 派生)', () => {
    const options = request()
    const once = appendRouteSwitchNotice(options, STEPFUN)
    const twice = appendRouteSwitchNotice(once, STEPFUN)
    assert.equal(twice.messages.length, 4) // 4 = 3 + 1,不会变成 5
    assert.equal(once.messages.length, 4)
  })
})

describe('0.5.2 red tests: DeepSeek replay envelope', () => {
  it('deepseek envelope adds route switch notice', () => {
    const deepseek = autoAssistant({ source: { provider: 'auto', model: 'auto', replayState: { response: { kind: 'deepseek-messages', version: 1, model: 'deepseek-flash' }, blocks: REASONING_THEN_TEXT } } })
    const fixed = appendRouteSwitchNotice(request([deepseek]), STEPFUN)
    assert.equal(fixed.messages.length, 2)
    assert.match(fixed.messages.at(-1).content[0].text, /generated by deepseek-flash;/u)
  })

  it('deepseek envelope reasoning is stripped for a pi-ai route without rewriting provider', () => {
    const deepseek = autoAssistant({ source: { provider: 'auto', model: 'auto', replayState: { response: { kind: 'deepseek-messages', version: 1, model: 'deepseek-flash' }, blocks: REASONING_THEN_TEXT } } })
    const fixed = restoreReplaySources(request([deepseek]), ROUTE).messages[0]
    assert.deepEqual(fixed.content.map((block) => block.type), ['text'])
    assert.equal(Object.hasOwn(fixed.source, 'provider'), true)
    assert.equal(fixed.source.provider, 'auto')
  })
})
describe('0.5.2 coverage: DeepSeek routes and unknown provider', () => {
  const deepseek = () => autoAssistant({ source: { provider: 'auto', model: 'auto', replayState: { response: { kind: 'deepseek-messages', version: 1, model: 'deepseek-flash' }, blocks: REASONING_THEN_TEXT } } })
  it('DeepSeek same model does not trigger notification', () => {
    const message = deepseek()
    assert.equal(appendRouteSwitchNotice(request([message]), { provider: 'deepseek-official', model: 'deepseek-flash' }).messages.length, 1)
  })
  it('keepThinking preserves both arrays by reference', () => {
    const message = autoAssistant()
    const fixed = restoreReplaySources(request([message]), STEPFUN, true).messages[0]
    assert.equal(fixed.content, message.content)
    assert.equal(fixed.source.replayState.blocks, message.source.replayState.blocks)
  })
  it('default false synchronously strips content and replay blocks', () => {
    const message = autoAssistant()
    const fixed = restoreReplaySources(request([message]), STEPFUN, false).messages[0]
    assert.deepEqual(fixed.content.map((block) => block.type), ['text'])
    assert.deepEqual(fixed.source.replayState.blocks.map((block) => block.type), ['text'])
  })
  it('keepThinking passed directly preserves both arrays by reference and still rewrites the source', () => {
    const options = request()
    const before = options.messages[1]
    const after = restoreReplaySources(options, STEPFUN, true).messages[1]
    // 跨路由 + 显式保留:content 与 replayState.blocks 两侧都不动(同一引用)
    assert.equal(after.content, before.content)
    assert.equal(after.source.replayState, before.source.replayState)
    assert.equal(after.source.replayState.blocks, before.source.replayState.blocks)
    assert.deepEqual(after.content.map((block) => block.type), ['reasoning', 'text'])
    // source 改写行为不受 keepThinking 影响(与不传第三参时同款:仍对齐到 replay 路由)
    assert.notEqual(after, before)
    assert.equal(after.source.provider, 'opencode-go')
    assert.equal(after.source.model, 'deepseek-v4.1-flash')
    assert.equal(Object.isFrozen(after), true)
    assert.equal(replayedAssistantCheck(after), null) // 保留思考后信封仍合法
    // 入参(深冻结)未被破坏
    assert.equal(before.source.provider, 'auto')
    assert.equal(before.source.model, 'auto')
    assert.deepEqual(before.content.map((block) => block.type), ['reasoning', 'text'])
  })

  it('keepThinking false or omitted strips both arrays in step and keeps the replay envelope valid', () => {
    const options = request()
    const before = options.messages[1]
    for (const keepThinking of [false, undefined]) {
      const label = `keepThinking=${String(keepThinking)}`
      const after = restoreReplaySources(options, STEPFUN, keepThinking).messages[1]
      assert.notEqual(after.content, before.content, label)
      assert.deepEqual(after.content.map((block) => block.type), ['text'], label) // content 侧摘掉
      assert.deepEqual(after.source.replayState.blocks.map((block) => block.type), ['text'], label) // blocks 侧同位摘掉
      assert.equal(after.content[0].text, '12121', label) // 正文逐字保留
      assert.equal(after.source.provider, 'opencode-go', label) // source 改写照旧
      assert.equal(after.source.model, 'deepseek-v4.1-flash', label)
      assert.equal(replayedAssistantCheck(after), null, label) // 等长 + 逐条同型仍通过
    }
    // 入参(深冻结)未被破坏
    assert.deepEqual(before.content.map((block) => block.type), ['reasoning', 'text'])
    assert.deepEqual(before.source.replayState.blocks.map((block) => block.type), ['reasoning', 'text'])
  })
  it('DeepSeek thinking-only message is removed', () => {
    const message = autoAssistant({ content: [{ type: 'reasoning', text: 'private' }], source: { provider: 'auto', model: 'auto', replayState: { response: { kind: 'deepseek-messages', version: 1, model: 'deepseek-flash' }, blocks: [{ type: 'reasoning' }] } } })
    assert.deepEqual(restoreReplaySources(request([message]), ROUTE).messages, [])
  })
  it('unknown provider is never written into the restored source', () => {
    const message = deepseek()
    const fixed = restoreReplaySources(request([message]), ROUTE).messages[0]
    assert.equal(Object.hasOwn(fixed.source, 'provider'), true)
    assert.equal(fixed.source.provider, 'auto')
    assert.equal(fixed.source.model, 'auto')
  })
  it('unknown provider labels use model only, never undefined prefix', () => {
    const fixed = appendRouteSwitchNotice(request([deepseek()]), STEPFUN)
    assert.match(fixed.messages.at(-1).content[0].text, /generated by deepseek-flash;/u)
    assert.doesNotMatch(fixed.messages.at(-1).content[0].text, /undefined\//u)
  })
})

describe('appendToolLoopBreak:把工具循环收尾(缺陷③)', () => {
  /** 目标路由:开了 breakToolLoop 的 DeepSeek 兜底路由。 */
  const LOOP_ROUTE = Object.freeze({ provider: 'deepseek-official', model: 'deepseek-flash', breakToolLoop: true })
  /** 同一路由但没开开关。 */
  const PLAIN_ROUTE = Object.freeze({ provider: 'deepseek-official', model: 'deepseek-flash' })

  /** 一条"带工具调用却没有思考块"的历史助手消息(现场:opencode-go 产出的回合)。 */
  function toolOnlyAssistant() {
    return Object.freeze({
      role: 'assistant',
      content: Object.freeze([Object.freeze({ type: 'tool-call', id: 'c1', name: 'read', arguments: '{}' })]),
      source: Object.freeze({
        kind: 'model',
        provider: 'auto',
        model: 'auto',
        replayState: Object.freeze({
          response: Object.freeze({
            kind: 'pi-ai', version: 2, api: 'openai-completions',
            provider: 'opencode-go', model: 'deepseek-v4.1-flash', stopReason: 'toolUse',
          }),
          blocks: Object.freeze([Object.freeze({ type: 'tool-call' })]),
        }),
      }),
    })
  }

  /** 与上面那条配对的工具结果 —— 它出现在末尾时才构成"工具循环"。 */
  function toolResult() {
    return Object.freeze({ role: 'tool', toolCallId: 'c1', content: Object.freeze([Object.freeze({ type: 'text', text: 'ok' })]) })
  }

  /** 末尾是工具结果的请求(现场第 114 步的形态)。 */
  function loopRequest() {
    return Object.freeze({
      provider: 'auto',
      model: 'auto',
      messages: Object.freeze([Object.freeze({ role: 'user', content: '开始' }), toolOnlyAssistant(), toolResult()]),
    })
  }

  it('三条判据全中 ⇒ 末尾追加一条用户角色的提示', () => {
    const options = loopRequest()
    const out = appendToolLoopBreak(options, LOOP_ROUTE)
    assert.notEqual(out, options, '需要追加时返回新对象')
    assert.equal(out.messages.length, options.messages.length + 1)
    const added = out.messages[out.messages.length - 1]
    assert.equal(added.role, 'user', '必须是用户角色,否则改不掉"以工具结果结尾"这个形态')
    assert.equal(added.source.kind, 'tool-loop')
    assert.equal(added.source.form, 'notice')
    assert.match(added.content[0].text, /tool loop notice/u)
    assert.match(added.content[0].text, /reasoning content/u)
    assert.equal(options.messages.length, 3, '原 options 不被改动')
  })

  it('目标路由没开开关(未声明 / false / 形状不对)⇒ 原样返回同一个对象', () => {
    const options = loopRequest()
    for (const route of [PLAIN_ROUTE, { ...PLAIN_ROUTE, breakToolLoop: false }, undefined, null, 'nope', { provider: 'x' }]) {
      assert.equal(appendToolLoopBreak(options, route), options)
    }
  })

  it('末尾不是工具结果 ⇒ 不追加(不在校验点上)', () => {
    const tailUser = Object.freeze({
      provider: 'auto',
      model: 'auto',
      messages: Object.freeze([toolOnlyAssistant(), Object.freeze({ role: 'user', content: '追问' })]),
    })
    assert.equal(appendToolLoopBreak(tailUser, LOOP_ROUTE), tailUser)
  })

  it('历史里没有"带工具调用却无思考"的助手消息 ⇒ 不追加(不打扰)', () => {
    const healthy = Object.freeze({
      provider: 'auto',
      model: 'auto',
      messages: Object.freeze([autoAssistant(), toolResult()]),
    })
    assert.equal(appendToolLoopBreak(healthy, LOOP_ROUTE), healthy)
  })

  it('只有工具结果、没有任何助手消息 ⇒ 不追加', () => {
    const bare = Object.freeze({ provider: 'auto', model: 'auto', messages: Object.freeze([toolResult()]) })
    assert.equal(appendToolLoopBreak(bare, LOOP_ROUTE), bare)
  })

  it('空 messages / 坏形状不抛错,原样返回', () => {
    const empty = Object.freeze({ provider: 'auto', model: 'auto', messages: Object.freeze([]) })
    assert.equal(appendToolLoopBreak(empty, LOOP_ROUTE), empty)
    assert.equal(appendToolLoopBreak(null, LOOP_ROUTE), null)
    assert.equal(appendToolLoopBreak({}, LOOP_ROUTE).messages, undefined)
  })

  it('与路由切换通知互斥:通知先追加(末尾变 user)则本函数不再追加', () => {
    const options = loopRequest()
    const noticed = appendRouteSwitchNotice(options, LOOP_ROUTE)
    assert.notEqual(noticed, options, '切换确实发生,通知已追加')
    assert.equal(noticed.messages[noticed.messages.length - 1].source.kind, 'model-selection')
    assert.equal(appendToolLoopBreak(noticed, LOOP_ROUTE), noticed, '末尾已是 user,不再追加')
  })

  it('只在出站副本里:调用后原消息对象逐字未变', () => {
    const options = loopRequest()
    const before = options.messages.map((message) => JSON.stringify(message))
    appendToolLoopBreak(options, LOOP_ROUTE)
    assert.deepEqual(options.messages.map((message) => JSON.stringify(message)), before)
  })
})
